#!/bin/bash

RELEASES_URL=https://www.kernel.org/releases.json

rm linux.tar.xz
if [ -z "$1" ]
  then source=$(curl -s $RELEASES_URL | jq -r '.latest_stable.version as $stable_version | .releases[] | select(.version == $stable_version) | .source');
  else source=$(curl -s $RELEASES_URL | jq -r ".releases[] | select(.version == \"$1\") | .source")
fi


echo downloading source $source
curl $source --output linux.tar.xz
rm -rf linux/
mkdir linux
tar -xJf linux.tar.xz -C linux --strip-components=1
./make_kernel_manual
